title: "LUMT - Useful Minecraft Tools"
description: "A list of useful minecraft websites, tools, software, mods, ..."
theme: minima
markdown: kramdown

minima:
  skin: dark
  nav_pages:
    - a/index.md
    - lumt.md
    - contributors.md

exclude:
  - README.md
  - .github/
  - .vscode
  - NOTES.md
  - CNAME
  - LICENSE
